### ISSUE TITLE
Planeación

### ISSUE THREAD

**Issue by TattaArias** [JhonTriana/Practica_Actividad#18]

**Comment by JhonTriana** [comment]
•	Temática: Revista de Novias y Novios
•	Nombre: ProBodas

**Comment by JhonTriana** [comment]
•	Establecer el compromiso de puntos
•	Realizar la lista de tareas plasmando la Historia de Usuario de la siguiente manera:

   HISTORIA TIPO 4 = Foto1 + Foto2 + Foto3 + Foto4 + Descripción1 
(ver la Fotografía 1)

•	Construir el product backlog en Zenhub de acuerdo con la lista de tareas y poniendo en la parte superior la historia de mayor prioridad.

•	Generar la gráfica del Burndown
